# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analytics_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from my_charts import OHLCChart, LineChart, MultiLineChart
from my_tables import MyTable
import pandas as pd
import numpy as np
import datetime
from statsmodels.tsa.api import adfuller, kpss
from statsmodels.api import OLS
from pandasmodel import PandasModel
import ccxt

class Analytics(QtWidgets.QWidget):
    def __init__(self, parent, zaur):
        super().__init__(parent)

        self.zaur = zaur
        self.tabs = QtWidgets.QTabWidget(self)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 901, 534))
        self.tabs.setStyleSheet("font: 75 12pt \"FreeMono Bold\";")


        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 901, 501))
        self.frame_5.setStyleSheet("font: 75 10.5pt \"FreeMono Bold\";")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_8.setGeometry(QtCore.QRect(240, 10, 231, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_31.setGeometry(QtCore.QRect(110, 40, 111, 61))
        self.pushButton_31.setObjectName("pushButton_31")
        self.comboBox_30 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_30.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.label_62 = QtWidgets.QLabel(self.groupBox_8)
        self.label_62.setGeometry(QtCore.QRect(20, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FreeMono Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(550, 0, 341, 501))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.frame_9)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 341, 501))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.frame_10 = QtWidgets.QFrame(self.tab_9)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 331, 471))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 27))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 181, 27))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 101, 27))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 121, 27))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 121, 27))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 231, 27))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(10, 250, 141, 27))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 81, 27))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setGeometry(QtCore.QRect(10, 330, 91, 27))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setGeometry(QtCore.QRect(270, 10, 51, 27))
        self.label_13.setObjectName("label_13")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 10, 111, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 50, 111, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 90, 111, 27))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 130, 111, 27))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 170, 111, 27))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 210, 71, 27))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 250, 111, 27))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 290, 111, 27))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_7.setGeometry(QtCore.QRect(100, 330, 111, 27))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_8.setGeometry(QtCore.QRect(230, 330, 91, 27))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(10, 370, 51, 27))
        self.label_18.setObjectName("label_18")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_10.setGeometry(QtCore.QRect(60, 370, 151, 27))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 370, 89, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 410, 201, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 410, 89, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_17.setGeometry(QtCore.QRect(100, 130, 91, 27))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_18.setGeometry(QtCore.QRect(100, 170, 91, 27))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.frame_15 = QtWidgets.QFrame(self.tab_10)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 331, 471))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_14 = QtWidgets.QLabel(self.frame_15)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 101, 27))
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 111, 27))
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.frame_15)
        self.label_21.setGeometry(QtCore.QRect(10, 130, 141, 27))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_15)
        self.label_22.setGeometry(QtCore.QRect(10, 170, 131, 27))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setGeometry(QtCore.QRect(10, 210, 231, 27))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_15)
        self.label_24.setGeometry(QtCore.QRect(10, 250, 141, 27))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_15)
        self.label_25.setGeometry(QtCore.QRect(10, 290, 101, 27))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_15)
        self.label_26.setGeometry(QtCore.QRect(10, 330, 81, 27))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_15)
        self.label_27.setGeometry(QtCore.QRect(270, 10, 51, 27))
        self.label_27.setObjectName("label_27")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 10, 111, 27))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 50, 181, 27))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 90, 121, 27))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_16.setGeometry(QtCore.QRect(180, 130, 141, 27))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_17.setGeometry(QtCore.QRect(180, 170, 141, 27))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_18.setGeometry(QtCore.QRect(250, 210, 71, 27))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_19.setGeometry(QtCore.QRect(170, 250, 151, 27))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_20.setGeometry(QtCore.QRect(140, 290, 181, 27))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_11.setGeometry(QtCore.QRect(100, 330, 111, 27))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_12.setGeometry(QtCore.QRect(230, 330, 91, 27))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_28 = QtWidgets.QLabel(self.frame_15)
        self.label_28.setGeometry(QtCore.QRect(10, 370, 41, 27))
        self.label_28.setObjectName("label_28")
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_13.setGeometry(QtCore.QRect(60, 370, 151, 27))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_9.setGeometry(QtCore.QRect(230, 370, 89, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 410, 201, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_11.setGeometry(QtCore.QRect(230, 410, 89, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_29.setGeometry(QtCore.QRect(50, 90, 81, 27))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setGeometry(QtCore.QRect(10, 90, 41, 27))
        self.label_31.setObjectName("label_31")
        self.label_40 = QtWidgets.QLabel(self.frame_15)
        self.label_40.setGeometry(QtCore.QRect(150, 90, 41, 27))
        self.label_40.setObjectName("label_40")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.frame_16 = QtWidgets.QFrame(self.tab_11)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 331, 471))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_29 = QtWidgets.QLabel(self.frame_16)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 121, 27))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_16)
        self.label_30.setGeometry(QtCore.QRect(10, 50, 121, 27))
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.frame_16)
        self.label_32.setGeometry(QtCore.QRect(10, 130, 141, 27))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_16)
        self.label_33.setGeometry(QtCore.QRect(10, 170, 131, 27))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_16)
        self.label_34.setGeometry(QtCore.QRect(10, 210, 231, 27))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setGeometry(QtCore.QRect(10, 250, 151, 27))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_16)
        self.label_36.setGeometry(QtCore.QRect(10, 290, 141, 27))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_16)
        self.label_37.setGeometry(QtCore.QRect(10, 330, 91, 27))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_16)
        self.label_38.setGeometry(QtCore.QRect(270, 10, 51, 27))
        self.label_38.setObjectName("label_38")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_21.setGeometry(QtCore.QRect(140, 10, 111, 27))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_22.setGeometry(QtCore.QRect(140, 50, 181, 27))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_23.setGeometry(QtCore.QRect(260, 90, 61, 27))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_24.setGeometry(QtCore.QRect(160, 130, 161, 27))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_25.setGeometry(QtCore.QRect(160, 170, 161, 27))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_26.setGeometry(QtCore.QRect(240, 210, 81, 27))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_27.setGeometry(QtCore.QRect(170, 250, 151, 27))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_28.setGeometry(QtCore.QRect(140, 290, 181, 27))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_14.setGeometry(QtCore.QRect(100, 330, 111, 27))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_15.setGeometry(QtCore.QRect(230, 330, 91, 27))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.label_39 = QtWidgets.QLabel(self.frame_16)
        self.label_39.setGeometry(QtCore.QRect(10, 370, 51, 27))
        self.label_39.setObjectName("label_39")
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_16.setGeometry(QtCore.QRect(80, 370, 131, 27))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 370, 89, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 410, 201, 51))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(230, 410, 89, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_50 = QtWidgets.QLabel(self.frame_16)
        self.label_50.setGeometry(QtCore.QRect(10, 90, 91, 27))
        self.label_50.setObjectName("label_50")
        self.comboBox_24 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_24.setGeometry(QtCore.QRect(100, 90, 71, 27))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_25 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_25.setGeometry(QtCore.QRect(180, 90, 71, 27))
        self.comboBox_25.setObjectName("comboBox_25")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_7.setGeometry(QtCore.QRect(240, 130, 301, 361))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.groupBox_7)
        self.tabWidget_7.setGeometry(QtCore.QRect(10, 30, 281, 321))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.tableView_6 = QtWidgets.QTableView(self.tab_16)
        self.tableView_6.setGeometry(QtCore.QRect(0, 0, 271, 291))
        self.tableView_6.setObjectName("tableView_6")
        self.tabWidget_7.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.tableView_7 = QtWidgets.QTableView(self.tab_17)
        self.tableView_7.setGeometry(QtCore.QRect(0, 0, 271, 291))
        self.tableView_7.setObjectName("tableView_7")
        self.tabWidget_7.addTab(self.tab_17, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tableView_8 = QtWidgets.QTableView(self.tab_21)
        self.tableView_8.setGeometry(QtCore.QRect(0, 0, 271, 291))
        self.tableView_8.setObjectName("tableView_8")
        self.tabWidget_7.addTab(self.tab_21, "")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 310, 221, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_29.setGeometry(QtCore.QRect(10, 130, 81, 41))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_30.setGeometry(QtCore.QRect(100, 130, 121, 41))
        self.pushButton_30.setObjectName("pushButton_30")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 211, 91))
        self.listWidget.setObjectName("listWidget")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 10, 221, 149))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 30, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 111, 27))
        self.label_2.setObjectName("label_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_5.setGeometry(QtCore.QRect(130, 70, 81, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 110, 81, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 160, 221, 150))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(10, 30, 61, 27))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.label_42.setObjectName("label_42")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_31.setGeometry(QtCore.QRect(70, 30, 141, 27))
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_32.setGeometry(QtCore.QRect(70, 70, 141, 27))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_28.setGeometry(QtCore.QRect(120, 110, 91, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.pushButton_32.setObjectName("pushButton_32")


        self.tabs.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_8.setGeometry(QtCore.QRect(0, 0, 901, 501))
        self.tabWidget_8.setObjectName("tabWidget_8")



        self.tabs.addTab(self.tab_5, "")
        self.databasetab = DatabaseTab(self.tabs, self.zaur)
        self.tabs.addTab(self.databasetab, "database")

        self.retranslateUi()
        self.tabs.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)


        self.set_default_timeframe()

        self.statarb_lines = [self.lineEdit_3, self.lineEdit_4, self.lineEdit_5, self.lineEdit_6, self.lineEdit_7,
                              self.lineEdit_8, self.lineEdit_9, self.lineEdit_10]

        self.momentum_lines = [self.lineEdit_13, self.lineEdit_14, self.lineEdit_15, self.lineEdit_16, self.lineEdit_17,
                               self.lineEdit_18, self.lineEdit_19, self.lineEdit_20, self.lineEdit_29]

        self.custom_lines = [self.lineEdit_21, self.lineEdit_22, self.lineEdit_23, self.lineEdit_24, self.lineEdit_25,
                             self.lineEdit_26, self.lineEdit_27, self.lineEdit_28]



        self.pushButton_28.clicked.connect(self.clear_pairs)
        self.pushButton_32.clicked.connect(self.send_to_algos)
        self.pushButton_8.clicked.connect(self.clear_statarb_config)
        self.pushButton_11.clicked.connect(self.clear_momentum_config)
        self.pushButton_14.clicked.connect(self.clear_custom_config)
        self.comboBox_5.currentTextChanged.connect(self.update_base_currency)
        self.pushButton_31.clicked.connect(self.analyze_data)


        QtCore.QMetaObject.connectSlotsByName(self)




    def analyze_data(self):
        coin1 = self.lineEdit_31.text()
        coin2 = self.lineEdit_32.text()
        timeframe = self.comboBox_30.currentText()
        interval = self.comboBox_6.currentText()

        if self.lineEdit_9.text():
            window = int(self.lineEdit_9.text())
        else:
            window = ''

        entry_z_score = float(self.lineEdit_5.text())
        stop_loss = float(self.lineEdit_7.text())

        print(timeframe)
        dfs = self.zaur.get_data2([coin1, coin2], timeframe, interval)

        df2 = pd.DataFrame(index=dfs[0].index, data={dfs[0].name: dfs[0].iloc[:, 3], dfs[1].name: dfs[1].iloc[:, 3]})
        analysis_df, results = self.zaur.analyze_data(df2, entry_z_score=entry_z_score, stop_loss=stop_loss, window=window)

        tab = AnalysisTabs(self.tabWidget_8, self.zaur, coin1.split('_')[0], coin2.split('_')[0], dfs, analysis_df, results, interval)
        self.tabWidget_8.addTab(tab, f'{coin1}_vs_{coin2}')
        self.tabs.setCurrentIndex(1)
        self.tabWidget_8.setCurrentIndex(-1)


    def update_base_currency(self):
        for label in [self.label_13, self.label_27, self.label_38]:
            label.setText(self.comboBox_5.currentText())


    def set_default_timeframe(self):
        self.comboBox_30.setCurrentText('3M')



    def send_to_algos(self):
        pair = f'{self.zaur.front.current_ticker}_{self.zaur.front.current_exchange.id}'
        if self.lineEdit_31.text():
            self.lineEdit_32.setText(pair)
        else:
            self.lineEdit_31.setText(pair)

    def update_intervals(self):
        self.comboBox_6.clear()
        try:
            self.comboBox_6.addItems(self.zaur.current_exchange.timeframes.keys())
        except Exception:
            pass

    def clear_pairs(self):
        self.lineEdit_31.clear()
        self.lineEdit_32.clear()

    def clear_statarb_config(self):
        for line in self.statarb_lines:
            line.clear()

    def clear_momentum_config(self):
        for line in self.momentum_lines:
            line.clear()

    def clear_custom_config(self):
        for line in self.custom_lines:
            line.clear()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_8.setTitle(_translate("Form", " data analysis n\' backtest"))
        self.pushButton_31.setText(_translate("Form", "analyze it!"))
        self.comboBox_30.setItemText(0, _translate("Form", "12h"))
        self.comboBox_30.setItemText(1, _translate("Form", "24h"))
        self.comboBox_30.setItemText(2, _translate("Form", "2d"))
        self.comboBox_30.setItemText(3, _translate("Form", "3d"))
        self.comboBox_30.setItemText(4, _translate("Form", "7d"))
        self.comboBox_30.setItemText(5, _translate("Form", "14d"))
        self.comboBox_30.setItemText(6, _translate("Form", "1M"))
        self.comboBox_30.setItemText(7, _translate("Form", "2M"))
        self.comboBox_30.setItemText(8, _translate("Form", "3M"))
        self.comboBox_30.setItemText(9, _translate("Form", "6M"))
        self.comboBox_30.setItemText(10, _translate("Form", "1y"))
        self.comboBox_30.setItemText(11, _translate("Form", "2y"))
        self.comboBox_30.setItemText(12, _translate("Form", "3y"))
        self.comboBox_30.setItemText(13, _translate("Form", "5y"))
        self.comboBox_30.setItemText(14, _translate("Form", "10y"))
        self.label_62.setText(_translate("Form", "timeframe"))
        self.label_4.setText(_translate("Form", "starting capital"))
        self.label_5.setText(_translate("Form", "trade size in % of capital"))
        self.label_6.setText(_translate("Form", "entry z-score"))
        self.label_7.setText(_translate("Form", "take profit"))
        self.label_8.setText(_translate("Form", "stop loss"))
        self.label_9.setText(_translate("Form", "stop algorithm (% of funds lost)"))
        self.label_10.setText(_translate("Form", "MA window"))
        self.label_11.setText(_translate("Form", "leverage"))
        self.label_12.setText(_translate("Form", "order types"))
        self.label_13.setText(_translate("Form", "USDT"))
        self.comboBox_7.setItemText(0, _translate("Form", "enter trade"))
        self.comboBox_7.setItemText(1, _translate("Form", "take profit"))
        self.comboBox_7.setItemText(2, _translate("Form", "stop loss"))
        self.comboBox_8.setItemText(0, _translate("Form", "limit"))
        self.comboBox_8.setItemText(1, _translate("Form", "market"))
        self.comboBox_8.setItemText(2, _translate("Form", "stop market"))
        self.label_18.setText(_translate("Form", "alert"))
        self.comboBox_10.setItemText(0, _translate("Form", "entered trade"))
        self.comboBox_10.setItemText(1, _translate("Form", "took profit"))
        self.comboBox_10.setItemText(2, _translate("Form", "stopped loss"))
        self.comboBox_10.setItemText(3, _translate("Form", "algorithm stopped"))
        self.pushButton_6.setText(_translate("Form", "add"))
        self.pushButton_7.setText(_translate("Form", "save"))
        self.pushButton_8.setText(_translate("Form", "clear"))
        self.comboBox_17.setItemText(0, _translate("Form", "z-score"))
        self.comboBox_17.setItemText(1, _translate("Form", "% gain"))
        self.comboBox_18.setItemText(0, _translate("Form", "z-score"))
        self.comboBox_18.setItemText(1, _translate("Form", "% loss"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("Form", "stat arb"))
        self.label_14.setText(_translate("Form", "starting cash"))
        self.label_19.setText(_translate("Form", "trade size in %"))
        self.label_21.setText(_translate("Form", "take profit (% gain)"))
        self.label_22.setText(_translate("Form", "stop loss (% loss)"))
        self.label_23.setText(_translate("Form", "stop algorithm (% of funds lost)"))
        self.label_24.setText(_translate("Form", "max open positions"))
        self.label_25.setText(_translate("Form", "max leverage"))
        self.label_26.setText(_translate("Form", "order types"))
        self.label_27.setText(_translate("Form", "USDT"))
        self.comboBox_11.setItemText(0, _translate("Form", "enter trade"))
        self.comboBox_11.setItemText(1, _translate("Form", "take profit"))
        self.comboBox_11.setItemText(2, _translate("Form", "stop loss"))
        self.comboBox_12.setItemText(0, _translate("Form", "limit"))
        self.comboBox_12.setItemText(1, _translate("Form", "market"))
        self.comboBox_12.setItemText(2, _translate("Form", "stop market"))
        self.label_28.setText(_translate("Form", "alert"))
        self.comboBox_13.setItemText(0, _translate("Form", "entered trade"))
        self.comboBox_13.setItemText(1, _translate("Form", "took profit"))
        self.comboBox_13.setItemText(2, _translate("Form", "stopped loss"))
        self.comboBox_13.setItemText(3, _translate("Form", "algorithm stopped"))
        self.pushButton_9.setText(_translate("Form", "add"))
        self.pushButton_10.setText(_translate("Form", "save"))
        self.pushButton_11.setText(_translate("Form", "clear"))
        self.label_31.setText(_translate("Form", "MA1"))
        self.label_40.setText(_translate("Form", "MA2"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("Form", "momentum"))
        self.label_29.setText(_translate("Form", "starting cash"))
        self.label_30.setText(_translate("Form", "trade size in %"))
        self.label_32.setText(_translate("Form", "take profit (% gain)"))
        self.label_33.setText(_translate("Form", "stop loss (% loss)"))
        self.label_34.setText(_translate("Form", "stop algorithm (% of funds lost)"))
        self.label_35.setText(_translate("Form", "max open positions"))
        self.label_36.setText(_translate("Form", "max leverage"))
        self.label_37.setText(_translate("Form", "order types"))
        self.label_38.setText(_translate("Form", "USDT"))
        self.comboBox_14.setItemText(0, _translate("Form", "enter trade"))
        self.comboBox_14.setItemText(1, _translate("Form", "take profit"))
        self.comboBox_14.setItemText(2, _translate("Form", "stop loss"))
        self.comboBox_15.setItemText(0, _translate("Form", "limit"))
        self.comboBox_15.setItemText(1, _translate("Form", "market"))
        self.comboBox_15.setItemText(2, _translate("Form", "stop market"))
        self.label_39.setText(_translate("Form", "alert"))
        self.comboBox_16.setItemText(0, _translate("Form", "entered trade"))
        self.comboBox_16.setItemText(1, _translate("Form", "took profit"))
        self.comboBox_16.setItemText(2, _translate("Form", "stopped loss"))
        self.comboBox_16.setItemText(3, _translate("Form", "algorithm stopped"))
        self.pushButton_12.setText(_translate("Form", "add"))
        self.pushButton_13.setText(_translate("Form", "save"))
        self.pushButton_14.setText(_translate("Form", "clear"))
        self.label_50.setText(_translate("Form", "entry when:"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("Form", "custom"))
        self.groupBox_7.setTitle(_translate("Form", " algorithm details n\' history"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_16), _translate("Form", "details"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_17), _translate("Form", "history"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_21), _translate("Form", "backtests"))
        self.groupBox_5.setTitle(_translate("Form", " algorithms"))
        self.pushButton_29.setText(_translate("Form", "delete"))
        self.pushButton_30.setText(_translate("Form", "save changes"))
        self.groupBox_11.setTitle(_translate("Form", "  algorithm name"))
        self.label_2.setText(_translate("Form", "base currency"))
        self.comboBox_5.setItemText(0, _translate("Form", "USDT"))
        self.comboBox_5.setItemText(1, _translate("Form", "PLN"))
        self.comboBox_5.setItemText(2, _translate("Form", "EUR"))
        self.comboBox_5.setItemText(3, _translate("Form", "USD"))
        self.comboBox_5.setItemText(4, _translate("Form", "GBP"))
        self.comboBox_5.setItemText(5, _translate("Form", "CHF"))
        self.comboBox_5.setItemText(6, _translate("Form", "JPY"))
        self.comboBox_5.setItemText(7, _translate("Form", "CNY"))
        self.comboBox_5.setItemText(8, _translate("Form", "BTC"))
        self.comboBox_5.setItemText(9, _translate("Form", "ETH"))
        self.comboBox_5.setItemText(10, _translate("Form", "LTC"))
        self.comboBox_5.setItemText(11, _translate("Form", "XRP"))
        self.comboBox_5.setItemText(12, _translate("Form", "XMR"))
        self.label_3.setText(_translate("Form", "interval"))
        self.groupBox_6.setTitle(_translate("Form", " pair selection"))
        self.label_41.setText(_translate("Form", "coin #1"))
        self.label_42.setText(_translate("Form", "coin #2"))
        self.pushButton_28.setText(_translate("Form", "clear"))
        self.pushButton_32.setText(_translate("Form", "add"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("Form", "algorithm wizard"))


        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("Form", "analyses"))






class AnalysisTabs(QtWidgets.QTabWidget):
    def __init__(self, parent, zaur, coin1, coin2, dfs, analysis_df, results, interval):
        super().__init__(parent)
        self.zaur = zaur
        self.parenttabs = parent
        self.df1 = dfs[0].copy()
        self.df2 = dfs[1].copy()

        self.results = results

        self.results['interval'] = interval

        self.coin1 = coin1
        self.coin2 = coin2

        self.analysis_df = analysis_df.copy()


        self.setGeometry(QtCore.QRect(0, 10, 901, 500))
        self.setStyleSheet("font: 75 11pt \"FreeMono Bold\";\n"
                            "background-color: rgb(20, 20, 40);\n"
                            "color: rgb(255, 255, 255);")

        self.ohlc1 = OHLCChart(self.df1, self)
        self.ohlc2 = OHLCChart(self.df2, self)
        self.spread_chart = LineChart(self.analysis_df['spread'], self)

        self.z_score_chart = LineChart(self.analysis_df.loc[10:, 'z_score'], self)
        cols2 = [col for col in self.analysis_df.columns if '100' in col]
        self.compare_chart = MultiLineChart(self.analysis_df[cols2], self)

        self.config = {'adf_reg': 'c', 'kpss_reg': 'c', 'adf_autolag': 'AIC', 'kpss_autolag': 'auto'}
        self.options = {'adf_reg': {'const': 'c', 'const+trend': 'ct', 'const+linear+quadratic trend': 'ctt', 'no const no trend': 'nc'},
                        'adf_lag': {'AIC': 'AIC', 'BIC': 'BIC', 't-stat': 't-stat'},
                        'kpss_reg': {'const': 'c', 'const+trend': 'ct'},
                        'kpss_lag': {'Hobijn': 'auto', 'Schwert': 'legacy'}}


        self.test_tab = QtWidgets.QWidget(self)
        self.test_tab.setGeometry(QtCore.QRect(0, 0, 901, 470))

        self.backtest_tab = QtWidgets.QWidget(self)
        self.backtest_tab.setGeometry(QtCore.QRect(0, 0, 901, 470))

        self.results_tab = QtWidgets.QWidget(self)
        self.results_tab.setGeometry(QtCore.QRect(0, 0, 901, 470))
        self.results_frame = QtWidgets.QFrame(self.results_tab)
        self.results_frame.setGeometry(QtCore.QRect(5, 5, 800, 460))

        self.pushButton_40 = QtWidgets.QPushButton(self)
        self.pushButton_40.setGeometry(QtCore.QRect(810, 0, 71, 31))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_40.setText("close")

        self.button2 = QtWidgets.QPushButton(self.results_frame)
        self.button2.setGeometry(QtCore.QRect(480, 31, 150, 60))
        self.button2.setText('save result')

        self.groupBox = QtWidgets.QGroupBox(self.test_tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 15, 901, 455))
        self.groupBox.setTitle('ADF:  regression   lags method                  KPSS:  regression   lags method')


        i = 0
        self.combos = dict()
        for k, v in self.options.items():
            combo = QtWidgets.QComboBox(self.groupBox)
            combo.addItems(v.keys())
            self.combos[k] = combo
            combo.setCurrentText(self.config[k])
            i += 1

        self.combos['adf_reg'].setGeometry(QtCore.QRect(45, 25, 80, 27))
        self.combos['adf_lag'].setGeometry(QtCore.QRect(130, 25, 80, 27))
        self.combos['kpss_reg'].setGeometry(QtCore.QRect(375, 25, 80, 27))
        self.combos['kpss_lag'].setGeometry(QtCore.QRect(470, 25, 80, 27))

        self.button = QtWidgets.QPushButton(self.groupBox)
        self.button.setGeometry(QtCore.QRect(800, 25, 70, 27))
        self.button.setText('rerun')

        self.addTab(self.ohlc1, self.coin1.split('_')[0])
        self.addTab(self.ohlc2, self.coin2.split('_')[0])
        self.addTab(self.spread_chart, "spread")
        self.addTab(self.z_score_chart, "z-score")
        self.addTab(self.compare_chart, "% compare chart")
        self.addTab(self.test_tab, "statistics")
        self.addTab(self.backtest_tab, "backtest log")
        self.addTab(self.results_tab, "results")

        self.show_statistical_tests()
        self.show_backtest_log()
        self.show_results()

        self.setCurrentIndex(-1)
        self.button.clicked.connect(self.rerun)
        self.button2.clicked.connect(self.save_results)
        self.pushButton_40.clicked.connect(self.close_analysis)


    def close_analysis(self):
        self.parenttabs.removeTab(self.parenttabs.currentIndex())

    def rerun(self):
        self.change_config()
        self.show_statistical_tests()


    def change_config(self):
        for k, v in self.combos.items():
            self.config[k] = self.options[k][v.currentText()]


    def show_statistical_tests(self):

        df = pd.DataFrame({self.coin1: self.df1['Close'], self.coin2: self.df2['Close']})
        stats = self.zaur.test_for_cointegration(df, self.config['adf_reg'], self.config['kpss_reg'],
                                                 self.config['adf_lag'], self.config['kpss_lag'])

        corr = self.df1['Close'].corr(self.df2['Close']).__round__(3)

        results_table = MyTable(self.groupBox)
        results_table.setGeometry(QtCore.QRect(5, 65, 270, 145))

        df2 = pd.DataFrame(index=['Pearson correlation', 'Hedge ratio', 'R^2', 'Adjusted R^2'], columns=['statistics'], data={'statistics':
                                    [corr, stats[0], stats[1], stats[2]]})

        model1 = PandasModel(df2)
        results_table.setModel(model1)

        tests_table = MyTable(self.groupBox)
        tests_table.setGeometry(QtCore.QRect(5, 220, 700, 85))
        model2 = PandasModel(stats[3])
        tests_table.setModel(model2)
        tests_table.setColumnWidth(0, 200)

        adfs_table = MyTable(self.groupBox)
        adfs_table.setGeometry(QtCore.QRect(5, 320, 190, 85))
        model3 = PandasModel(pd.DataFrame(stats[4]))
        adfs_table.setModel(model3)
        #adfs_table.setColumnWidth(0, 190)




    def show_backtest_log(self):

        self.backtest_table = MyTable(self.backtest_tab)
        self.backtest_table.setGeometry(QtCore.QRect(0, 10, 888, 408))
        self.analysis_df.index = self.analysis_df.index.map(lambda x: ccxt.Exchange.iso8601(x).replace('T', ' ').replace('Z', '')[:-7])
        model = PandasModel(self.analysis_df)
        self.backtest_table.setModel(model)
        self.backtest_table.setSortingEnabled(False)
        self.backtest_table.setHorizontalScrollBar(QtWidgets.QScrollBar())



    def show_results(self):

        self.results_table = MyTable(self.results_frame)
        self.results_table.setGeometry(QtCore.QRect(5, 5, 400, 450))

        self.results_table.setSortingEnabled(False)
        model2 = PandasModel(pd.DataFrame(self.results))
        self.results_table.setModel(model2)
        self.results_table.setColumnWidth(0, 500)


    def save_results(self):
        try:
            results = pd.read_csv('results.csv', index=True)
            results.iloc[len(results)] = self.results
            results.to_csv('results.csv')

        except FileNotFoundError:
            results = pd.DataFrame(columns=[self.results.index.values])
            results.iloc[0] = self.results
            results.to_csv('results.csv')






class DatabaseTab(QtWidgets.QWidget):
    def __init__(self, parent, zaur):
        super().__init__(parent)
        self.zaur = zaur
        self.setObjectName("Form")
        self.resize(901, 501)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 901, 501))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")

        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 580, 401))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableView = MyTable(self.groupBox_2)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 570, 291))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(200, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")


        self.current_exchange = None

        try:
            self.update_tables()
        except:
            pass

        self.retranslateUi()

        self.pushButton.clicked.connect(self.update_tables)
        self.pushButton_2.clicked.connect(self.drop_table)
        QtCore.QMetaObject.connectSlotsByName(self)


    def update_tables(self):
        tables = self.zaur.db.table_list()
        t = []

        for table in tables:
            if '_' in table[0]:
                t.append(table[0])

        self.tables = pd.DataFrame(index=t, columns=['start date', 'end date'])

        for table in t:
            start = self.zaur.db.execute_read_query(f"""SELECT MIN("Date") FROM '{table}';""")[0][0]
            end = self.zaur.db.execute_read_query(f"""SELECT MAX("Date") FROM '{table}';""")[0][0]
            self.tables.loc[table, 'start date'] = ccxt.Exchange.iso8601(start)[:16].replace('T', ' ')
            self.tables.loc[table, 'end date'] = ccxt.Exchange.iso8601(end)[:16].replace('T', ' ')


        self.model = PandasModel(self.tables)
        self.tableView.setModel(self.model)
        self.tableView.setColumnWidth(0, 175)
        self.tableView.setColumnWidth(1, 175)


    def select_exchange(self):
        self.current_exchange = self.comboBox.currentText()
        #self.comboBox_2.addItems()


    def drop_table(self):
        current_index = self.tableView.currentIndex().row()
        table_name = self.tables.index[current_index]
        self.zaur.db.drop_table(table_name)
        self.tables.drop(table_name, inplace=True)
        self.model = PandasModel(self.tables)
        self.tableView.setModel(self.model)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "  database"))
        self.groupBox_2.setTitle(_translate("Form", "tables"))
        self.pushButton.setText(_translate("Form", "update"))
        self.pushButton_2.setText(_translate("Form", "delete"))

